- name: Disable Telnet on Aruba CX
  hosts: aruba_test
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Disable Telnet
      ansible.netcommon.cli_command:
        command: |
          system-view
          undo telnet-server
          write memory
