---
- name: KADIN DOGUM HP Disable TELNET SET
  hosts: KD_hp_switches
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Run the Necessary Commands  by Cagri
      ansible.netcommon.cli_command:
        command: |
          system-view
          undo telnet server enable
          save safely force
